### ISSUE TITLE
i have error: Field 'value' and 'name' not exists in referenced class \faravaghi\jalaliDatePicker\jalaliDatePicker

### ISSUE THREAD

**Issue by Global90** [faravaghi/yii2-jalali-datepicker#2]
i have error: Field '**value**' and '**name**' not exists in referenced class \faravaghi\jalaliDatePicker\jalaliDatePicker

**# used without model**

```
<?php
use faravaghi\jalaliDatePicker\jalaliDatePicker;

echo jalaliDatePicker::widget([
    'name'  => 'date',
    'value'  => '1395/01/31',
	'options' => [
			'format' => 'yyyy/mm/dd',
			'startDate' => '1395/05/12',
			'endDate' => '1395/10/10',
			'viewformat' => 'yyyy/mm/dd',
			'placement' => 'right',
			'todayBtn' => 'linked',
			'id' => 'date',
			'class' => 'form-control' 
	],
]);
?>
```

**Comment by faravaghi** [comment]
This widget extends from **InputWidget** that **name** and **value** Defined and it inherits. This code runs correctly, and no error.  
I've used it many times....

**Comment by Global90** [comment]
Please Check images. i have error in IDE and Page

![1](https://user-images.githubusercontent.com/8215910/27000706-40625cac-4dcd-11e7-8b07-c26337ad292c.jpg)
![2](https://user-images.githubusercontent.com/8215910/27000705-4061e1aa-4dcd-11e7-984e-3d73de264882.jpg)

**Comment by faravaghi** [comment]
Please use the latest version of the widget.

**Comment by Global90** [comment]
after reinstall:
```
composer require --prefer-dist faravaghi/yii2-jalali-datepicker "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

not fix my problem.
