### ISSUE TITLE
اشکال در استفاده از تاریخ بدون model

### ISSUE THREAD

**Issue by MasoudZeini** [faravaghi/yii2-jalali-datepicker#3]
سلام . برای استفاده از این ویجت بدون مدل مشکل وجود داره

**Comment by msh-shf** [comment]
دوست عزیز مشکل داره این چیزی که شما گذاشتی توی داکیومنت هم هست. خودتون اصلا تست گرفتین!!؟

![image](https://user-images.githubusercontent.com/12235182/62193619-63584280-b38d-11e9-93ce-e3011203ad17.png)
