### ISSUE TITLE
this error remains

### ISSUE THREAD

**Issue by MasoudZeini** [faravaghi/yii2-jalali-datepicker#4]
Dude

this extension dose not work without model . many other people are saying this

but you are resisting in this case!!!!!!!!!!!!

**Comment by faravaghi** [comment]
Hi dear friend,
You are free to use this widget and if you see that it is not working, please write a new widget or use another widget.
In addition, in your city, two people are called many other people!!!
I used this widget in more than 10 different projects in different ways and I did not have problems.
Good luck.
